name: game_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.1
  flame_tiled: ^1.12.0
  flame_oxygen: ^0.1.8+4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/rogue.png
    - assets/images/seasons_tiles.png
    - assets/tiles/
    - assets/tiles/farm__tiles.tmx
    - assets/tiles/farm_csv.tmx
    - assets/tiles/demo.tmx
    - assets/tiles/seasons_tiles.tsx
    - assets/images/chimneyBase_E.png
    - assets/images/chimneyBase_N.png
    - assets/images/chimneyBase_S.png
    - assets/images/chimneyBase_W.png
    - assets/images/chimneyTop_E.png
    - assets/images/chimneyTop_N.png
    - assets/images/chimneyTop_S.png
    - assets/images/chimneyTop_W.png
    - assets/images/corn_E.png
    - assets/images/corn_N.png
    - assets/images/corn_S.png
    - assets/images/corn_W.png
    - assets/images/cornDouble_E.png
    - assets/images/cornDouble_N.png
    - assets/images/cornDouble_S.png
    - assets/images/cornDouble_W.png
    - assets/images/cornYoung_E.png
    - assets/images/cornYoung_N.png
    - assets/images/cornYoung_S.png
    - assets/images/cornYoung_W.png
    - assets/images/cornYoungDouble_E.png
    - assets/images/cornYoungDouble_N.png
    - assets/images/cornYoungDouble_S.png
    - assets/images/cornYoungDouble_W.png
    - assets/images/dirt_E.png
    - assets/images/dirt_N.png
    - assets/images/dirt_S.png
    - assets/images/dirt_W.png
    - assets/images/dirtFarmland_E.png
    - assets/images/dirtFarmland_N.png
    - assets/images/dirtFarmland_S.png
    - assets/images/dirtFarmland_W.png
    - assets/images/fenceHigh_E.png
    - assets/images/fenceHigh_N.png
    - assets/images/fenceHigh_S.png
    - assets/images/fenceHigh_W.png
    - assets/images/fenceHighBroken_E.png
    - assets/images/fenceHighBroken_N.png
    - assets/images/fenceHighBroken_S.png
    - assets/images/fenceHighBroken_W.png
    - assets/images/fenceLow_E.png
    - assets/images/fenceLow_N.png
    - assets/images/fenceLow_S.png
    - assets/images/fenceLow_W.png
    - assets/images/fenceLowBroken_E.png
    - assets/images/fenceLowBroken_N.png
    - assets/images/fenceLowBroken_S.png
    - assets/images/fenceLowBroken_W.png
    - assets/images/hay_E.png
    - assets/images/hay_N.png
    - assets/images/hay_S.png
    - assets/images/hay_W.png
    - assets/images/hayBales_E.png
    - assets/images/hayBales_N.png
    - assets/images/hayBales_S.png
    - assets/images/hayBales_W.png
    - assets/images/hayBalesStacked_E.png
    - assets/images/hayBalesStacked_N.png
    - assets/images/hayBalesStacked_S.png
    - assets/images/hayBalesStacked_W.png
    - assets/images/iso_tiles.png
    - assets/images/ladderStand_E.png
    - assets/images/ladderStand_N.png
    - assets/images/ladderStand_S.png
    - assets/images/ladderStand_W.png
    - assets/images/ladderStandBroken_E.png
    - assets/images/ladderStandBroken_N.png
    - assets/images/ladderStandBroken_S.png
    - assets/images/ladderStandBroken_W.png
    - assets/images/ladderStraight_E.png
    - assets/images/ladderStraight_N.png
    - assets/images/ladderStraight_S.png
    - assets/images/ladderStraight_W.png
    - assets/images/planks_E.png
    - assets/images/planks_N.png
    - assets/images/planks_S.png
    - assets/images/planks_W.png
    - assets/images/planksCornerLeft_E.png
    - assets/images/planksCornerLeft_N.png
    - assets/images/planksCornerLeft_S.png
    - assets/images/planksCornerLeft_W.png
    - assets/images/planksCornerRight_E.png
    - assets/images/planksCornerRight_N.png
    - assets/images/planksCornerRight_S.png
    - assets/images/planksCornerRight_W.png
    - assets/images/planksHigh_E.png
    - assets/images/planksHigh_N.png
    - assets/images/planksHigh_S.png
    - assets/images/planksHigh_W.png
    - assets/images/planksHighOld_E.png
    - assets/images/planksHighOld_N.png
    - assets/images/planksHighOld_S.png
    - assets/images/planksHighOld_W.png
    - assets/images/planksHighSlope_E.png
    - assets/images/planksHighSlope_N.png
    - assets/images/planksHighSlope_S.png
    - assets/images/planksHighSlope_W.png
    - assets/images/planksHole_E.png
    - assets/images/planksHole_N.png
    - assets/images/planksHole_S.png
    - assets/images/planksHole_W.png
    - assets/images/planksOld_E.png
    - assets/images/planksOld_N.png
    - assets/images/planksOld_S.png
    - assets/images/planksOld_W.png
    - assets/images/planksSide_E.png
    - assets/images/planksSide_N.png
    - assets/images/planksSide_S.png
    - assets/images/planksSide_W.png
    - assets/images/planksSideVertical_E.png
    - assets/images/planksSideVertical_N.png
    - assets/images/planksSideVertical_S.png
    - assets/images/planksSideVertical_W.png
    - assets/images/rogue.png
    - assets/images/roof_E.png
    - assets/images/roof_N.png
    - assets/images/roof_S.png
    - assets/images/roof_W.png
    - assets/images/roofCorner_E.png
    - assets/images/roofCorner_N.png
    - assets/images/roofCorner_S.png
    - assets/images/roofCorner_W.png
    - assets/images/roofInnerCorner_E.png
    - assets/images/roofInnerCorner_N.png
    - assets/images/roofInnerCorner_S.png
    - assets/images/roofInnerCorner_W.png
    - assets/images/roofSingle_E.png
    - assets/images/roofSingle_N.png
    - assets/images/roofSingle_S.png
    - assets/images/roofSingle_W.png
    - assets/images/roofSingleWall_E.png
    - assets/images/roofSingleWall_N.png
    - assets/images/roofSingleWall_S.png
    - assets/images/roofSingleWall_W.png
    - assets/images/sack_E.png
    - assets/images/sack_N.png
    - assets/images/sack_S.png
    - assets/images/sack_W.png
    - assets/images/sacksCrate_E.png
    - assets/images/sacksCrate_N.png
    - assets/images/sacksCrate_S.png
    - assets/images/sacksCrate_W.png
    - assets/images/seasons_tiles.png
    - assets/images/selector.png
    - assets/images/tileset_Full.png
    - assets/images/woodWall_E.png
    - assets/images/woodWall_N.png
    - assets/images/woodWall_S.png
    - assets/images/woodWall_W.png
    - assets/images/woodWallCorner_E.png
    - assets/images/woodWallCorner_N.png
    - assets/images/woodWallCorner_S.png
    - assets/images/woodWallCorner_W.png
    - assets/images/woodWallCross_E.png
    - assets/images/woodWallCross_N.png
    - assets/images/woodWallCross_S.png
    - assets/images/woodWallCross_W.png
    - assets/images/woodWallDiagional_E.png
    - assets/images/woodWallDiagional_N.png
    - assets/images/woodWallDiagional_S.png
    - assets/images/woodWallDiagional_W.png
    - assets/images/woodWallDoorClosed_E.png
    - assets/images/woodWallDoorClosed_N.png
    - assets/images/woodWallDoorClosed_S.png
    - assets/images/woodWallDoorClosed_W.png
    - assets/images/woodWallDoorOpen_E.png
    - assets/images/woodWallDoorOpen_N.png
    - assets/images/woodWallDoorOpen_S.png
    - assets/images/woodWallDoorOpen_W.png
    - assets/images/woodWallDoorway_E.png
    - assets/images/woodWallDoorway_N.png
    - assets/images/woodWallDoorway_S.png
    - assets/images/woodWallDoorway_W.png
    - assets/images/woodWallEmpty_E.png
    - assets/images/woodWallEmpty_N.png
    - assets/images/woodWallEmpty_S.png
    - assets/images/woodWallEmpty_W.png
    - assets/images/woodWallEmptyCross_E.png
    - assets/images/woodWallEmptyCross_N.png
    - assets/images/woodWallEmptyCross_S.png
    - assets/images/woodWallEmptyCross_W.png
    - assets/images/woodWallEmptyDiagonal_E.png
    - assets/images/woodWallEmptyDiagonal_N.png
    - assets/images/woodWallEmptyDiagonal_S.png
    - assets/images/woodWallEmptyDiagonal_W.png
    - assets/images/woodWallEmptyOpen_E.png
    - assets/images/woodWallEmptyOpen_N.png
    - assets/images/woodWallEmptyOpen_S.png
    - assets/images/woodWallEmptyOpen_W.png
    - assets/images/woodWallGateClosed_E.png
    - assets/images/woodWallGateClosed_N.png
    - assets/images/woodWallGateClosed_S.png
    - assets/images/woodWallGateClosed_W.png
    - assets/images/woodWallGateOpen_E.png
    - assets/images/woodWallGateOpen_N.png
    - assets/images/woodWallGateOpen_S.png
    - assets/images/woodWallGateOpen_W.png
    - assets/images/woodWallGateway_E.png
    - assets/images/woodWallGateway_N.png
    - assets/images/woodWallGateway_S.png
    - assets/images/woodWallGateway_W.png
    - assets/images/woodWallHole_E.png
    - assets/images/woodWallHole_N.png
    - assets/images/woodWallHole_S.png
    - assets/images/woodWallHole_W.png
    - assets/images/woodWallHoleCross_E.png
    - assets/images/woodWallHoleCross_N.png
    - assets/images/woodWallHoleCross_S.png
    - assets/images/woodWallHoleCross_W.png
    - assets/images/woodWallHoleDiagonal_E.png
    - assets/images/woodWallHoleDiagonal_N.png
    - assets/images/woodWallHoleDiagonal_S.png
    - assets/images/woodWallHoleDiagonal_W.png
    - assets/images/woodWallRoofLeft_E.png
    - assets/images/woodWallRoofLeft_N.png
    - assets/images/woodWallRoofLeft_S.png
    - assets/images/woodWallRoofLeft_W.png
    - assets/images/woodWallRoofRight_E.png
    - assets/images/woodWallRoofRight_N.png
    - assets/images/woodWallRoofRight_S.png
    - assets/images/woodWallRoofRight_W.png
    - assets/images/woodWallSupport_E.png
    - assets/images/woodWallSupport_N.png
    - assets/images/woodWallSupport_S.png
    - assets/images/woodWallSupport_W.png
    - assets/images/woodWallWindow_E.png
    - assets/images/woodWallWindow_N.png
    - assets/images/woodWallWindow_S.png
    - assets/images/woodWallWindow_W.png
    - assets/images/woodWallWindowGlass_E.png
    - assets/images/woodWallWindowGlass_N.png
    - assets/images/woodWallWindowGlass_S.png
    - assets/images/woodWallWindowGlass_W.png
